<a href="https://colab.research.google.com/github/thejapamarthy/Python-strings-and-if-condition/blob/main/Data_Visualization_(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/afeld/python-public-policy/blob/main/hw_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data visualization



1. Complete the **Coding** exercise below.
1. **Tutorial:** Go the first third of [Time Series Analysis with Pandas](https://www.dataquest.io/blog/tutorial-time-series-analysis-with-pandas/), up until the "Visualizing time series data" section.

In [ ]:
%pip install --upgrade --quiet plotly

### Step 1

Load the request per capita dataset from https://nyu.box.com/shared/static/m8zlqkoore2qq1n84a8as3r3o5hxwwth.csv as `requests_by_cd` and display it.

In [ ]:
# your code here
# reading the dataset
import pandas as pd
requests_by_cd = pd.read_csv('https://nyu.box.com/shared/static/m8zlqkoore2qq1n84a8as3r3o5hxwwth.csv')
requests_by_cd.head() # getting first 5 values

   borocd    Borough  ... count_of_311_requests  request_per_capita
0     112  Manhattan  ...                 81403            0.428392
1     405     Queens  ...                 71506            0.422637
2     412     Queens  ...                 70362            0.311448
3     301   Brooklyn  ...                 68104            0.393476
4     303   Brooklyn  ...                 66360            0.433768

[5 rows x 6 columns]

### Step 2

Make a [histogram](https://plotly.com/python/histograms/) of the requests per capita.

In [ ]:
# your code here
import pandas as pd
import plotly.express as px
#requests_by_cd['borocd']
#fig = [px.histogram(requests_by_cd, x='2010 Population')
#fig.show()
requests_by_cd = pd.read_csv('https://nyu.box.com/shared/static/m8zlqkoore2qq1n84a8as3r3o5hxwwth.csv')
#df=pd.read_csv('https://nyu.box.com/shared/static/m8zlqkoore2qq1n84a8as3r3o5hxwwth.csv',low_memory=False)
fig = px.histogram(requests_by_cd,
                   x='request_per_capita',
                   title='Volume of 311 requests, 2018-2019',
                   labels={'request_per_capita': '311 requests per capita'})
fig.show()

## In-class exercise 2

Take [the scatterplot example from the lecture](https://colab.research.google.com/github/afeld/python-public-policy/blob/main/lecture_3.ipynb#scrollTo=L1smfBSEc5x9) and [add a trendline](https://plotly.com/python/linear-fits/).

In [ ]:
# your code here
fig = px.scatter(requests_by_cd,
                 x='2010 Population',
                 y='count_of_311_requests',
                 hover_data=['borocd', 'CD Name'],color="Borough",
                 trendline='ols')

fig.show()

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning:

pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.

## Coding

We are going to look at the population count of different community districts over time. First, let's make sure Plotly is up-to-date to avoid issues later.

In [ ]:
%pip install --upgrade --quiet plotly
import plotly.express as px

### Step 1

Read the data from the [New York City Population By Community Districts](https://data.cityofnewyork.us/City-Government/New-York-City-Population-By-Community-Districts/xi7c-iiu2/data) data set into a DataFrame called `pop_by_cd`, then display it. To get the URL:

1. Visit the page linked above.
1. Click `Export`.
1. Right-click `CSV`.
1. Click `Copy Link Address` (or `Location`, depending on your browser).

In [ ]:
# your code here
import pandas as pd
pop_by_cd=pd.read_csv('https://data.cityofnewyork.us/api/views/xi7c-iiu2/rows.csv?accessType=DOWNLOAD', low_memory=False)
print(pop_by_cd)
pop_by_cd.head()

          Borough  CD Number  ... 2000 Population  2010 Population
0           Bronx          1  ...           82159            91497
1           Bronx          2  ...           46824            52246
2           Bronx          3  ...           68574            79762
3           Bronx          4  ...          139563           146441
4           Bronx          5  ...          128313           128200
5           Bronx          6  ...           75688            83268
6           Bronx          7  ...          141411           139286
7           Bronx          8  ...          101332           101731
8           Bronx          9  ...          167859           172298
9           Bronx         10  ...          115948           120392
10          Bronx         11  ...          110706           113232
11          Bronx         12  ...          149077           152344
12       Brooklyn          1  ...          160338           173083
13       Brooklyn          2  ...           98620            99617
14       Brooklyn          3  ...          143867           152985
15       Brooklyn          4  ...          104358           112634
16       Brooklyn          5  ...          173198           182896
17       Brooklyn          6  ...          104054           104709
18       Brooklyn          7  ...          120063           126230
19       Brooklyn          8  ...           96076            96317
20       Brooklyn          9  ...          104014            98429
21       Brooklyn         10  ...          122542           124491
22       Brooklyn         11  ...          172129           181981
23       Brooklyn         12  ...          185046           191382
24       Brooklyn         13  ...          106120           104278
25       Brooklyn         14  ...          168806           160664
26       Brooklyn         15  ...          160319           159650
27       Brooklyn         16  ...           85343            86468
28       Brooklyn         17  ...          165753           155252
29       Brooklyn         18  ...          194653           193543
30      Manhattan          1  ...           34420            60978
31      Manhattan          2  ...           93119            90016
32      Manhattan          3  ...          164407           163277
33      Manhattan          4  ...           87479           103245
34      Manhattan          5  ...           44028            51673
35      Manhattan          6  ...          136152           142745
36      Manhattan          7  ...          207699           209084
37      Manhattan          8  ...          217063           219920
38      Manhattan          9  ...          111724           110193
39      Manhattan         10  ...          107109           115723
40      Manhattan         11  ...          117743           120511
41      Manhattan         12  ...          208414           190020
42         Queens          1  ...          211220           191105
43         Queens          2  ...          109920           113200
44         Queens          3  ...          169083           171576
45         Queens          4  ...          167005           172598
46         Queens          5  ...          165911           169190
47         Queens          6  ...          115967           113257
48         Queens          7  ...          242952           247354
49         Queens          8  ...          146594           151107
50         Queens          9  ...          141608           143317
51         Queens         10  ...          127274           122396
52         Queens         11  ...          116404           116431
53         Queens         12  ...          223602           225919
54         Queens         13  ...          196284           188593
55         Queens         14  ...          106686           114978
56  Staten Island          1  ...          162609           175756
57  Staten Island          2  ...          127071           132003
58  Staten Island          3  ...          152908           160209

[59 rows x 8 columns]

  Borough  CD Number  ... 2000 Population  2010 Population
0   Bronx          1  ...           82159            91497
1   Bronx          2  ...           46824            52246
2   Bronx          3  ...           68574            79762
3   Bronx          4  ...          139563           146441
4   Bronx          5  ...          128313           128200

[5 rows x 8 columns]

### Step 2

Prepare the data. Use the following code to [reshape](https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html) the DataFrame to have one row per community district per Census year.

In [ ]:
# turn the population columns into rows
populations = pd.melt(pop_by_cd, id_vars=['Borough', 'CD Number', 'CD Name'], var_name='year', value_name='population')

# turn the years into numbers
populations.year = populations.year.str.replace(' Population', '').astype(int)

populations

           Borough  CD Number  ...  year  population
0            Bronx          1  ...  1970      138557
1            Bronx          2  ...  1970       99493
2            Bronx          3  ...  1970      150636
3            Bronx          4  ...  1970      144207
4            Bronx          5  ...  1970      121807
..             ...        ...  ...   ...         ...
290         Queens         13  ...  2010      188593
291         Queens         14  ...  2010      114978
292  Staten Island          1  ...  2010      175756
293  Staten Island          2  ...  2010      132003
294  Staten Island          3  ...  2010      160209

[295 rows x 5 columns]

### Step 3

Create a new `manhattan` DataFrame that has only the populations for that borough.

In [ ]:
# your code here
#creating a new dataframe with pop values from Manhattan
manhattan= populations.loc[populations["Borough"]=='Manhattan']
print(manhattan)

       Borough  CD Number                           CD Name  year  population
30   Manhattan          1        Battery Park City, Tribeca  1970        7706
31   Manhattan          2           Greenwich Village, Soho  1970       84337
32   Manhattan          3        Lower East Side, Chinatown  1970      181845
33   Manhattan          4                  Chelsea, Clinton  1970       83601
34   Manhattan          5         Midtown Business District  1970       31076
35   Manhattan          6       Stuyvesant Town, Turtle Bay  1970      122465
36   Manhattan          7        West Side, Upper West Side  1970      212422
37   Manhattan          8                   Upper East Side  1970      200851
38   Manhattan          9  Manhattanville, Hamilton Heights  1970      113606
39   Manhattan         10                    Central Harlem  1970      159267
40   Manhattan         11                       East Harlem  1970      154662
41   Manhattan         12        Washington Heights, Inwood  1970      180561
89   Manhattan          1        Battery Park City, Tribeca  1980       15918
90   Manhattan          2           Greenwich Village, Soho  1980       87069
91   Manhattan          3        Lower East Side, Chinatown  1980      154848
92   Manhattan          4                  Chelsea, Clinton  1980       82164
93   Manhattan          5         Midtown Business District  1980       39544
94   Manhattan          6       Stuyvesant Town, Turtle Bay  1980      127554
95   Manhattan          7        West Side, Upper West Side  1980      206669
96   Manhattan          8                   Upper East Side  1980      204305
97   Manhattan          9  Manhattanville, Hamilton Heights  1980      103038
98   Manhattan         10                    Central Harlem  1980      105641
99   Manhattan         11                       East Harlem  1980      114569
100  Manhattan         12        Washington Heights, Inwood  1980      179941
148  Manhattan          1        Battery Park City, Tribeca  1990       25366
149  Manhattan          2           Greenwich Village, Soho  1990       94105
150  Manhattan          3        Lower East Side, Chinatown  1990      161617
151  Manhattan          4                  Chelsea, Clinton  1990       84431
152  Manhattan          5         Midtown Business District  1990       43507
153  Manhattan          6       Stuyvesant Town, Turtle Bay  1990      133748
154  Manhattan          7        West Side, Upper West Side  1990      210993
155  Manhattan          8                   Upper East Side  1990      210880
156  Manhattan          9  Manhattanville, Hamilton Heights  1990      106978
157  Manhattan         10                    Central Harlem  1990       99519
158  Manhattan         11                       East Harlem  1990      110508
159  Manhattan         12        Washington Heights, Inwood  1990      198192
207  Manhattan          1        Battery Park City, Tribeca  2000       34420
208  Manhattan          2           Greenwich Village, Soho  2000       93119
209  Manhattan          3        Lower East Side, Chinatown  2000      164407
210  Manhattan          4                  Chelsea, Clinton  2000       87479
211  Manhattan          5         Midtown Business District  2000       44028
212  Manhattan          6       Stuyvesant Town, Turtle Bay  2000      136152
213  Manhattan          7        West Side, Upper West Side  2000      207699
214  Manhattan          8                   Upper East Side  2000      217063
215  Manhattan          9  Manhattanville, Hamilton Heights  2000      111724
216  Manhattan         10                    Central Harlem  2000      107109
217  Manhattan         11                       East Harlem  2000      117743
218  Manhattan         12        Washington Heights, Inwood  2000      208414
266  Manhattan          1        Battery Park City, Tribeca  2010       60978
267  Manhattan          2           Greenwich Village, Soho  2010       90016
268  Manhattan          3        Lower East Side, Chinatown  2010      163277
269  Manhattan          4                  Chelsea, Clinton  2010      103245
270  Manhattan          5         Midtown Business District  2010       51673
271  Manhattan          6       Stuyvesant Town, Turtle Bay  2010      142745
272  Manhattan          7        West Side, Upper West Side  2010      209084
273  Manhattan          8                   Upper East Side  2010      219920
274  Manhattan          9  Manhattanville, Hamilton Heights  2010      110193
275  Manhattan         10                    Central Harlem  2010      115723
276  Manhattan         11                       East Harlem  2010      120511
277  Manhattan         12        Washington Heights, Inwood  2010      190020

### Step 4

Create a line chart of the population over time for each community district in Manhattan. There should be one line for each.

See the Plotly [Line Plot with column encoding color](https://plotly.com/python/line-charts/#line-plot-with-column-encoding-color) examples.

In [ ]:
# your code here
import plotly.express as px
fig = px.line(manhattan, x="year", y="population", color='CD Name')
fig.show()

### Step 5

We are going to do some mapping using the `pop_by_cd` DataFrame from before. To do so, we need `borocd`s. Create that column with the values filled in. (See [Lecture 2](https://colab.research.google.com/github/afeld/python-public-policy/blob/main/lecture_2.ipynb#scrollTo=Pq24B8pRC_FM).)

In [ ]:
# your code here
def recode_borocd_pop(row):
  if row.Borough == 'Manhattan':
    return str(100 + row['CD Number'])
  elif row.Borough == 'Bronx':
    return str(200 + row['CD Number'])
  elif row.Borough == 'Brooklyn':
    return str(300 + row['CD Number'])
  elif row.Borough == 'Queens':
    return str(400 + row['CD Number'])
  elif row.Borough == 'Staten Island':
    return str(500 + row['CD Number'])
  else:
    return 'Invalid BoroCD'
pop_by_cd['borocd'] = pop_by_cd.apply(recode_borocd_pop, axis=1)
pop_by_cd

          Borough  CD Number  ... 2010 Population  borocd
0           Bronx          1  ...           91497     201
1           Bronx          2  ...           52246     202
2           Bronx          3  ...           79762     203
3           Bronx          4  ...          146441     204
4           Bronx          5  ...          128200     205
5           Bronx          6  ...           83268     206
6           Bronx          7  ...          139286     207
7           Bronx          8  ...          101731     208
8           Bronx          9  ...          172298     209
9           Bronx         10  ...          120392     210
10          Bronx         11  ...          113232     211
11          Bronx         12  ...          152344     212
12       Brooklyn          1  ...          173083     301
13       Brooklyn          2  ...           99617     302
14       Brooklyn          3  ...          152985     303
15       Brooklyn          4  ...          112634     304
16       Brooklyn          5  ...          182896     305
17       Brooklyn          6  ...          104709     306
18       Brooklyn          7  ...          126230     307
19       Brooklyn          8  ...           96317     308
20       Brooklyn          9  ...           98429     309
21       Brooklyn         10  ...          124491     310
22       Brooklyn         11  ...          181981     311
23       Brooklyn         12  ...          191382     312
24       Brooklyn         13  ...          104278     313
25       Brooklyn         14  ...          160664     314
26       Brooklyn         15  ...          159650     315
27       Brooklyn         16  ...           86468     316
28       Brooklyn         17  ...          155252     317
29       Brooklyn         18  ...          193543     318
30      Manhattan          1  ...           60978     101
31      Manhattan          2  ...           90016     102
32      Manhattan          3  ...          163277     103
33      Manhattan          4  ...          103245     104
34      Manhattan          5  ...           51673     105
35      Manhattan          6  ...          142745     106
36      Manhattan          7  ...          209084     107
37      Manhattan          8  ...          219920     108
38      Manhattan          9  ...          110193     109
39      Manhattan         10  ...          115723     110
40      Manhattan         11  ...          120511     111
41      Manhattan         12  ...          190020     112
42         Queens          1  ...          191105     401
43         Queens          2  ...          113200     402
44         Queens          3  ...          171576     403
45         Queens          4  ...          172598     404
46         Queens          5  ...          169190     405
47         Queens          6  ...          113257     406
48         Queens          7  ...          247354     407
49         Queens          8  ...          151107     408
50         Queens          9  ...          143317     409
51         Queens         10  ...          122396     410
52         Queens         11  ...          116431     411
53         Queens         12  ...          225919     412
54         Queens         13  ...          188593     413
55         Queens         14  ...          114978     414
56  Staten Island          1  ...          175756     501
57  Staten Island          2  ...          132003     502
58  Staten Island          3  ...          160209     503

[59 rows x 9 columns]

### Step 6

Create a `change` column on the `pop_by_cd` DataFrame with the difference between the 2000 and 2010 population counts, then display the DataFrame.

In [ ]:
# your code here
pop_by_cd['change']= pop_by_cd['2010 Population']-pop_by_cd['2000 Population']
pop_by_cd

          Borough  CD Number  ... borocd  change
0           Bronx          1  ...    201    9338
1           Bronx          2  ...    202    5422
2           Bronx          3  ...    203   11188
3           Bronx          4  ...    204    6878
4           Bronx          5  ...    205    -113
5           Bronx          6  ...    206    7580
6           Bronx          7  ...    207   -2125
7           Bronx          8  ...    208     399
8           Bronx          9  ...    209    4439
9           Bronx         10  ...    210    4444
10          Bronx         11  ...    211    2526
11          Bronx         12  ...    212    3267
12       Brooklyn          1  ...    301   12745
13       Brooklyn          2  ...    302     997
14       Brooklyn          3  ...    303    9118
15       Brooklyn          4  ...    304    8276
16       Brooklyn          5  ...    305    9698
17       Brooklyn          6  ...    306     655
18       Brooklyn          7  ...    307    6167
19       Brooklyn          8  ...    308     241
20       Brooklyn          9  ...    309   -5585
21       Brooklyn         10  ...    310    1949
22       Brooklyn         11  ...    311    9852
23       Brooklyn         12  ...    312    6336
24       Brooklyn         13  ...    313   -1842
25       Brooklyn         14  ...    314   -8142
26       Brooklyn         15  ...    315    -669
27       Brooklyn         16  ...    316    1125
28       Brooklyn         17  ...    317  -10501
29       Brooklyn         18  ...    318   -1110
30      Manhattan          1  ...    101   26558
31      Manhattan          2  ...    102   -3103
32      Manhattan          3  ...    103   -1130
33      Manhattan          4  ...    104   15766
34      Manhattan          5  ...    105    7645
35      Manhattan          6  ...    106    6593
36      Manhattan          7  ...    107    1385
37      Manhattan          8  ...    108    2857
38      Manhattan          9  ...    109   -1531
39      Manhattan         10  ...    110    8614
40      Manhattan         11  ...    111    2768
41      Manhattan         12  ...    112  -18394
42         Queens          1  ...    401  -20115
43         Queens          2  ...    402    3280
44         Queens          3  ...    403    2493
45         Queens          4  ...    404    5593
46         Queens          5  ...    405    3279
47         Queens          6  ...    406   -2710
48         Queens          7  ...    407    4402
49         Queens          8  ...    408    4513
50         Queens          9  ...    409    1709
51         Queens         10  ...    410   -4878
52         Queens         11  ...    411      27
53         Queens         12  ...    412    2317
54         Queens         13  ...    413   -7691
55         Queens         14  ...    414    8292
56  Staten Island          1  ...    501   13147
57  Staten Island          2  ...    502    4932
58  Staten Island          3  ...    503    7301

[59 rows x 10 columns]

### Step 7

Let make a [choropleth map](https://www.data-to-viz.com/graph/choropleth.html) showing the population change for each community district that we just calculated. Adapt [the `.choropleth_mapbox()` example in Lecture 3](https://colab.research.google.com/github/afeld/python-public-policy/blob/main/lecture_3.ipynb#scrollTo=5lLS8zmn6oHP).

If you get an error about `choropleth_mapbox() got an unexpected keyword argument 'featureidkey'`, go back and do the `Setup` above.

In [ ]:
# your code here
import json
geojson = 'https://data.cityofnewyork.us/api/geospatial/yfnk-k7r4?method=export&format=GeoJSON'

fig = px.choropleth_mapbox(pop_by_cd,
                           geojson=geojson,
                           locations='borocd',
                           featureidkey='properties.boro_cd',
                           color='change',
                           hover_data=['CD Name'],
                           center = {'lat': 40.73, 'lon': -73.98},
                           zoom=9,
                           mapbox_style='carto-positron')
#fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(height=700)
fig.show()

### Step 8

***Analysis: Washington Heights and Inwood (the tall skinny community district at the top of Manhattan) are "up and coming" neighborhoods. Why might you guess the population decreased?***

YOUR ANSWER HERE
Could be due to migration/ under reporting

Then, read the first three paragraphs of the `Demographics` section of [An Economic Snapshot of Washington Heights and Inwood from June 2015](https://www.osc.state.ny.us/osdc/rpt2-2016.pdf#page=2).

## Tutorials

1. Read the [Data Design Standards](https://xdgov.github.io/data-design-standards/)